#!/usr/bin/env bun

import { $, app } from "@gutenye/script.js";

const HELP = `
`;

app.help(HELP);

app.cmd("tw", "[Test] Run tests in watch mode").add(async ({ argv }) => {
  await $`bun run test:watch ${argv}`;
});

app.cmd("t", "[Test] Run tests once").add(async ({ argv }) => {
  await $`bun run test ${argv}`;
});

app.cmd("l", "[Test] Run lint").add(async ({ argv }) => {
  await $`bun run lint ${argv}`;
});
